config/routes.rb
StockeryArduino::Application.routes.draw do
  match "reminder/thanks/:email" => "reminder#thanks", :as => 'reminder_thanks', :constraints => {:email => /[^\/]+/ }
  post  "reminder/create"

  resources :portfolios

  root :to => 'pages#home'

end

app/models/portfolio.rb
class Portfolio
  include MongoMapper::Document

  many :stocks 

  key :name, String, :required => true, :unique => true
  key :email, String, :required => true, :format => /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  key :url, String

  validate :ensure_same_name, :on => :update
  validates_associated :stocks

  after_validation :create_url

  def to_param
    url
  end

  def average
    average = 0

    unless stocks.nil?
      quote_fetcher = Stockery::Quote.new

      stocks.each do |stock|
        quote_data = quote_fetcher.get_status(stock.symbol)

        average += quote_data[:change_procent].to_f unless quote_data.nil?
      end

      sprintf("%0.02f", average)
    else
      -9999
    end
  end

  private

    def create_url
      self.url = self.name.to_url if self.url.blank?
    end

    def ensure_same_name
      if !name_was.nil? && name_was != name
        errors.add(:name, "You can't change the name of the portfolio")

        false
      end
    end
end

app/models/stock.rb
class Stock
  include MongoMapper::EmbeddedDocument

  belongs_to :portfolio

  key :symbol, String, :required => true
  key :name, String

  validates_length_of :symbol, :minimum => 1
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    @title = "Home"

    # @port = Portfolio.new
  end

end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController

  def show
    @port = Portfolio.find_by_url(params[:id])

    unless @port.nil?
      respond_to do |format|
        format.json { render :json => @port.to_json(
          :methods => :average, 
          :except => [:id, :url], 
          :include => {
            :stocks => { :only => [:name, :symbol]}
          }
        )}

        format.html do
          @title = "Portfolio '#{@port.name}'"
        end
      end
    else
      redirect_to root_path, :notice => 'The portfolio you requested did not exist.'
    end
  end

  def create
    @port = Portfolio.new(params[:portfolio])

    if @port.save
      PortfolioMailer.notify_creator(@port, edit_portfolio_url(@port.url)).deliver

      redirect_to edit_portfolio_path(@port.url), :success => 'Portfolio created with success.'
    else
      @title = 'Home'

      errors = ''
      
      @port.errors.messages.each { |key, message| errors += "#{key.capitalize} #{message[0]}" }

      flash.now[:error] = "Error creating the portfolio. #{errors}"
      
      render 'pages/home'
    end
  end

  def update
    @port = Portfolio.find_by_url(params[:id])

    if has_stocks?(params[:portfolio][:stocks])
      stocks = []

      params[:portfolio][:stocks].each do |stock|
        stocks << stock unless stock[:symbol].blank?
      end

      params[:portfolio][:stocks] = stocks
    end

    if has_stocks?(params[:portfolio][:stocks]) && @port.update_attributes(params[:portfolio])
      redirect_to portfolio_path(@port.url), :success => 'Portfolio updated with success.'
    else
      # TODO I don't want to reset name to name_was ... 
      params[:portfolio][:name] = params[:id]
      @port.name = params[:id]

      flash.now[:error] = 'Error updating the portfolio.'

      render 'edit'
    end 
  end

  def destroy
  end

  def edit
    @title = 'Edit Portfolio'
    
    @port = Portfolio.find_by_url(params[:id])
    @port.stocks.build  
  end

  private

    def has_stocks?(stocks)
      !stocks.nil? && stocks.size > 0
    end

end

app/controllers/reminder_controller.rb
class ReminderController < ApplicationController

  def thanks
    @email = params[:email]
  end

  def create
    ports = Portfolio.find_all_by_email(params[:email])

    unless ports.nil? || ports.size == 0
      portfolios = []

      ports.each do |port|
        portfolios << {:name => port.name, :link => edit_portfolio_url(port.url, :host => request.host)} unless port.url.blank?
      end

      ReminderMailer.remind_portfolios(params[:email], portfolios).deliver

      redirect_to reminder_thanks_path(:email => params[:email]), :success => "Your portfolio info was mailed to #{params[:email]}"
    else
      redirect_to root_path, :notice => 'E-mail address was not found'  
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def title
    @title ||= "Home"

    "#{@title} | Stockery - Arduino Portfolio Manager"
  end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/portfolio_helper.rb
module PortfolioHelper

  def add_extra_stock_link(name, html_options = {})
    link_to_function name, "$('#stocks').append('#{escape_javascript render(:partial => 'stock', :object => Stock.new)}')", html_options
  end

  def remove_extra_stock_link(name, html_options = {})
    link_to_function name, "$(this).parent().parent().parent().remove();", html_options
  end

end

app/helpers/reminder_helper.rb
module ReminderHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= title
    
    %link{:rel => 'shortcut icon', :href => '/assets/favicon.png'}

    = stylesheet_link_tag    "style"
    = javascript_include_tag "application"
    = csrf_meta_tags

  %body
  
  .container
    %header
      %a{:href => "#{root_path}", :class => 'logo'}
      Stocks in a box
      %br
      %span 
        powered by 
        %a{:href => 'http://github.com/pierot/stockery'}= "Stockery"

    - flash.each do |key, value|
      %div{:class => "alert-message block-message #{key}", 'data-alert' => 'alert'}
        %a{:href => '#', :class => 'close'} x
        = value

    = yield

app/views/pages/home.html.haml
%h1 Create your portfolio

= form_for :portfolio, :url => portfolios_path, :html => {:method => :post} do |form|
  %fieldset
    .clearfix
      = form.label :name
      .input
        = form.text_field :name, :class => 'xlarge'
    
    .clearfix
      = form.label :email
      .input
        = form.text_field :email, :class => 'xlarge'
    
    .actions
      = form.submit "Create portfolio", :class => 'btn large primary'

%h2 Looking to edit an existing portfolio?

%p 
  Give us your e-mail address and we'll drop everything you need to know in your mailbox.

= form_tag reminder_create_path, :method => :post do
  %fieldset
    .clearfix
      = label_tag :email, 'E-mail'
      .input
        = text_field_tag 'email', '', :class => 'xnormal'

    .actions
      = submit_tag 'Send it over please!', :class => 'btn info'

app/views/portfolios/_stock.html.haml
%div#stock_item
  = fields_for 'portfolio[stocks]', stock, :index => nil do |f|
    .clearfix
      = f.label :name
      .input
        = f.text_field :name, :class => 'xlarge'
  
    .clearfix
      = f.label :symbol
      .input
        = f.text_field :symbol, :class => 'xlarge'

        = remove_extra_stock_link 'X', :class => 'btn danger small'

app/views/portfolios/edit.html.haml
%h1= "Edit portfolio '#{@port.name}'"

= form_for @port, :url => portfolio_path(@port.url) do |form|
  %fieldset
    .clearfix
      = form.label :name
      .input
        = form.text_field :name, :class => 'xlarge'
    
    .clearfix
      = form.label :email
      .input
        = form.text_field :email, :class => 'xlarge'
   
    %div#stocks.clearfix
      %legend Add stock symbols (min 1 required)
      %br
      = render :partial => 'stock', :collection => @port.stocks

    .actions
      = add_extra_stock_link 'Add another stock symbol', :class => 'btn info small'
    
    .actions
      = form.submit "Save portfolio", :class => 'btn large primary'

app/views/portfolios/show.html.haml
%h1= "Portfolio '#{@port.name}'"

%h4 Portfolio information
= @port.name
%br
= @port.email

%br
%br

%h4 Stocks included in the portfolio
%table.zebra-striped.stocks
  %thead
    %tr
      %td #
      %td Stock symbol
      %td Stock name (optional)
  %tbody
    - @port.stocks.each_with_index do |stock, index|
      %tr
        %td= index
        %td= stock.symbol
        %td= stock.name

= link_to "Edit portfolio", edit_portfolio_path(@port.url), :class => 'btn info small'
%a{:href => "#{portfolio_url(@port.url)}.json", :class => 'btn small', :id => 'json-link', 'data-content' => 'Use this link in your application', :title => 'JSON output format'} JSON output

app/views/reminder/thanks.html.haml
%h1 Portfolio information has been sent

%p= "You will receive all the portfolio informatio that is linked to #{@email}."

= link_to 'Back to home', root_path